create table if not exists contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  subject text,
  message text
);

alter table contacts enable row level security;

create policy "Enable insert for all users" on contacts for insert with check (true);
