import requests

project_ref = "gnvyrpcfdqhkpgbfzfwo"
token = "sbp_6f5b3ff451f4be7a60d5ae7ab5df344d3efefdc5"
url = f"https://api.supabase.com/v1/projects/{project_ref}/query"

sql = """
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null
);
alter table contacts enable row level security;
drop policy if exists "Allow public inserts" on contacts;
create policy "Allow public inserts" on contacts for insert with check (true);
"""

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

data = {
    "query": sql
}

print(f"Executing SQL on {project_ref}...")
response = requests.post(url, json=data, headers=headers)

if response.status_code == 200 or response.status_code == 201:
    print("Success!")
    print(response.json())
else:
    print(f"Error: {response.status_code}")
    print(response.text)
