const https = require('https');

const projectRef = "gnvyrpcfdqhkpgbfzfwo";
const token = "sbp_6f5b3ff451f4be7a60d5ae7ab5df344d3efefdc5";

const sql = `
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null
);
alter table contacts enable row level security;
drop policy if exists "Allow public inserts" on contacts;
create policy "Allow public inserts" on contacts for insert with check (true);
`;

const data = JSON.stringify({ query: sql });

const options = {
    hostname: 'api.supabase.com',
    path: `/v1/projects/${projectRef}/query`,
    method: 'POST',
    headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'Content-Length': data.length
    }
};

const req = https.request(options, (res) => {
    let body = '';
    res.on('data', (chunk) => body += chunk);
    res.on('end', () => {
        console.log(`Status: ${res.statusCode}`);
        console.log('Response:', body);
    });
});

req.on('error', (error) => {
    console.error('Error:', error);
});

req.write(data);
req.end();
